const API='https://tenderbase-final-api.onrender.com/api/v1';
let page=1;const limit=12;let total=0;
const $=id=>document.getElementById(id);
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'})}
function params(){const p=new URLSearchParams({page,limit});const q=$('q').value.trim(),province=$('province').value,status=$('status').value,tenderType=$('tenderType').value,department=$('department').value.trim();if(q)p.set('q',q);if(province)p.set('province',province);if(status)p.set('status',status);if(tenderType)p.set('tenderType',tenderType);if(department)p.set('department',department);return p}
async function load(){ $('results').innerHTML='<div class="loading">Loading tenders…</div>'; $('empty').classList.add('hidden'); try{const r=await fetch(`${API}/tenders?${params()}`);if(!r.ok)throw new Error('API request failed');const data=await r.json();total=data.total??data.meta?.total??0;const items=data.data??data.tenders??data.results??[];$('totalCount').textContent=Number(total).toLocaleString();$('resultText').textContent=`${Number(total).toLocaleString()} matching tenders`;render(items);$('pageText').textContent=`Page ${page} of ${Math.max(1,Math.ceil(total/limit))}`;$('prev').disabled=page<=1;$('next').disabled=page>=Math.ceil(total/limit)}catch(e){$('results').innerHTML='<div class="empty">Unable to load tender data. Please try again.</div>';console.error(e)}}
function render(items){if(!items.length){$('results').innerHTML='';$('empty').classList.remove('hidden');return}$('results').innerHTML=items.map(t=>{const buyer=t.buyer?.name||t.procuringEntity?.name||t.buyerName||t.procuringEntityName||'Buyer not listed';const type=t.procurementMethodDetails||t.tenderType||'';const category=t.category||t.mainProcurementCategory||'';return `<article class="card" data-id="${esc(t.id||t.ocid||'')}"><div class="card-top"><div><div class="title">${esc(t.title||t.description||'Untitled tender')}</div><div class="ref">${esc(t.id||t.reference||t.tenderNumber||t.ocid||'')}</div></div><div class="close-date">Closes <strong>${esc(fmtDate(t.closingDate||t.tenderPeriod?.endDate||t.closeDate))}</strong></div></div><div class="meta"><span class="pill">${esc(t.province||'South Africa')}</span>${category?`<span class="pill">${esc(category)}</span>`:''}${type?`<span class="pill">${esc(type)}</span>`:''}<span class="pill">${esc(buyer)}</span></div></article>`}).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openTender(c.dataset.id))}
async function openTender(id){if(!id)return;$('modal').classList.remove('hidden');$('modalBody').innerHTML='<div class="loading">Loading tender details…</div>';try{const r=await fetch(`${API}/tenders/${encodeURIComponent(id)}`);if(!r.ok)throw new Error();const t=await r.json();const x=t.data||t.tender||t;const buyer=x.buyer?.name||x.procuringEntity?.name||x.buyerName||'Not listed';$('modalBody').innerHTML=`<p class="eyebrow">TENDER DETAILS</p><h2 class="modal-title">${esc(x.title||x.description||'Untitled tender')}</h2><div class="muted">${esc(x.id||x.reference||x.ocid||'')}</div><div class="detail-grid"><div><div class="detail-label">Status</div><div class="detail-value">${esc(x.status||'—')}</div></div><div><div class="detail-label">Closing</div><div class="detail-value">${esc(fmtDate(x.closingDate||x.tenderPeriod?.endDate))}</div></div><div><div class="detail-label">Province</div><div class="detail-value">${esc(x.province||'—')}</div></div><div><div class="detail-label">Buyer</div><div class="detail-value">${esc(buyer)}</div></div><div><div class="detail-label">Category</div><div class="detail-value">${esc(x.category||x.mainProcurementCategory||'—')}</div></div><div><div class="detail-label">Tender type</div><div class="detail-value">${esc(x.procurementMethodDetails||x.tenderType||'—')}</div></div></div><div class="detail-label">Description</div><div class="detail-value">${esc(x.description||x.title||'—')}</div>`}catch(e){$('modalBody').innerHTML='<div class="empty">Tender details could not be loaded.</div>';console.error(e)}}
$('searchBtn').onclick=()=>{page=1;load()};$('q').addEventListener('keydown',e=>{if(e.key==='Enter'){page=1;load()}});['province','status','tenderType','department','sort'].forEach(id=>$(id).addEventListener('change',()=>{page=1;load()}));$('prev').onclick=()=>{if(page>1){page--;load()}};$('next').onclick=()=>{if(page<Math.ceil(total/limit)){page++;load()}};$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.add('hidden')};load();
